program inteligent;


uses
  Forms,
  frm_connection in 'frm_connection.pas' {connection: TDataModule},
  frm_inteligent in 'frm_inteligent.pas' {frmInteligent},
  global in 'global.pas',
  frm_setup in 'frm_setup.pas' {frmSetup},
  frm_barra in 'frm_barra.pas' {frmBarra: TFrame},
  frm_equipos in 'frm_equipos.pas' {frmEquipos},
  frm_trinomios in 'frm_trinomios.pas' {frmTrinomios},
  frm_turnos in 'frm_turnos.pas' {frmTurnos},
  frm_Recursos_pernocta in 'frm_Recursos_pernocta.pas' {frmRecursosPernocta},
  Utilerias in 'Utilerias.pas',
  frm_gruposxprograma in 'frm_gruposxprograma.pas' {frmGruposxPrograma},
  frm_Consumibles in 'frm_Consumibles.pas' {frmConsumibles},
  frm_acerca in 'frm_acerca.pas' {frmAcerca},
  frm_proveedores in 'frm_proveedores.pas' {frmProveedores},
  frm_deptos in 'frm_deptos.pas' {frmDeptos},
  frm_TipoMovto in 'frm_TipoMovto.pas' {frmMovtos},
  frm_GruposUsuarios in 'frm_GruposUsuarios.pas' {frmGrupos},
  frm_CalculoAvancesxPartida in 'frm_CalculoAvancesxPartida.pas' {frmCalculoAvancesxPartida},
  frm_tramitedepermisos in 'frm_tramitedepermisos.pas' {frmTramitedePermisos},
  frm_DistribucionPrograma in 'frm_DistribucionPrograma.pas' {frmDistribucionPrograma},
  frm_actividadesxgrupo in 'frm_actividadesxgrupo.pas' {frmActividadesxGrupo},
  frm_ConsultadeActividades4 in 'frm_ConsultadeActividades4.pas' {frmConsultaActividad4},
  frm_AjustaOrden in 'frm_AjustaOrden.pas' {frmAjustaOrden},
  frm_CalculoAvancesPaquetes in 'frm_CalculoAvancesPaquetes.pas' {frmCalculoAvancesPaquetes},
  frm_personal in 'frm_personal.pas' {frmPersonal},
  frm_polizas in 'frm_polizas.pas' {frmPolizas},
  frm_paquetesdeequipo in 'frm_paquetesdeequipo.pas' {frmPaqueteEquipo},
  frm_AvancesFinancieros in 'frm_AvancesFinancieros.pas' {frmAvancesFinancieros},
  frm_AvisosAlertas in 'frm_AvisosAlertas.pas' {frmAvisosAlertas},
  frm_Reprogramacion in 'frm_Reprogramacion.pas' {frmReprogramacion},
  frm_comentariosxanexo in 'frm_comentariosxanexo.pas' {frmComentariosxAnexo},
  frm_diasfestivos in 'frm_diasfestivos.pas' {frmDiasFestivos},
  frm_ConsultaxDescripcion in 'frm_ConsultaxDescripcion.pas' {frmConsultaxDescripcion},
  frm_recursosxanexo in 'frm_recursosxanexo.pas' {frmRecursosxAnexo},
  frm_bitacora2 in 'frm_bitacora2.pas' {frmBitacora2},
  frm_OrdendeCambio in 'frm_OrdendeCambio.pas' {frmOrdendeCambio},
  frm_retecionesypenas in 'frm_retecionesypenas.pas' {frmRetencionesyPenas},
  frm_activos in 'frm_activos.pas' {frmActivos},
  frm_factordecosto in 'frm_factordecosto.pas' {frmFactordeCosto},
  frm_compara2 in 'frm_compara2.pas' {frmComparativo2},
  frm_SqlExportar in 'frm_SqlExportar.pas' {frmSqlExportar},
  frm_SqlManager in 'frm_SqlManager.pas' {frmSqlManager},
  frm_importaciondedatos in 'frm_importaciondedatos.pas' {frmImportaciondeDatos},
  frm_platicas in 'frm_platicas.pas' {frmPlaticas},
  frm_programas in 'frm_programas.pas' {frmProgramas},
  frm_contratosxordenes in 'frm_contratosxordenes.pas' {frmOrdenesxUsuario},
  frm_personalprogramado in 'frm_personalprogramado.pas' {frmPersonalProgramado},
  frm_generado in 'frm_generado.pas' {frmGenerado},
  frm_bitacoradepartamental_2 in 'frm_bitacoradepartamental_2.pas' {frmBitacoraDepartamental_2},
  frm_bitacoraxalcance in 'frm_bitacoraxalcance.pas' {frmBitacoraxAlcance},
  frm_PendientesNew in 'frm_PendientesNew.pas' {frmPendientesNew},
  frm_ConsultadeActividades5 in 'frm_ConsultadeActividades5.pas' {frmConsultaActividad5},
  frm_SqlImportar in 'frm_SqlImportar.pas' {frmSqlImportar},
  frm_ControlDirecto in 'frm_ControlDirecto.pas' {frmControlDirecto},
  frm_ValidaEstimacion in 'frm_ValidaEstimacion.pas' {frmValidaEstimacion},
  frm_ConsultadeActividades2 in 'frm_ConsultadeActividades2.pas' {frmConsultaActividad2},
  frm_ConsultadeActividades in 'frm_ConsultadeActividades.pas' {frmConsultaActividad},
  frm_Kardex in 'frm_Kardex.pas' {frmKardex},
  frm_seguridad in 'frm_seguridad.pas' {frmSeguridad},
  frm_cambiapassword in 'frm_cambiapassword.pas' {frmcambiopassword},
  frm_ReportePeriodo in 'frm_ReportePeriodo.pas' {frmReportePeriodo},
  frm_acceso in 'frm_acceso.pas' {frmacceso},
  frm_jornadasdiarias in 'frm_jornadasdiarias.pas' {frmJornadasDiarias},
  frm_Proyeccion in 'frm_Proyeccion.pas' {frmProyeccion},
  frm_FichaTecnica in 'frm_FichaTecnica.pas' {frmFichaTecnica},
  frm_personalconsolidado in 'frm_personalconsolidado.pas' {frmPersonalConsolidado},
  frm_SintesisGerencial in 'frm_SintesisGerencial.pas' {frmSintesisGerencial},
  frm_firmantes in 'frm_firmantes.pas' {frmFirmas},
  frm_ConsultadeActividades3 in 'frm_ConsultadeActividades3.pas' {frmConsultaActividad3},
  frmReporteDiarioGerencial in 'frmReporteDiarioGerencial.pas' {frmReporteGerencial},
  frm_warningdia in 'frm_warningdia.pas' {frmWarningDia},
  frm_tipsdia in 'frm_tipsdia.pas' {frmTipsDia},
  frm_abrereporte in 'frm_abrereporte.pas' {frmAbreReporte},
  frm_usuarios in 'frm_usuarios.pas' {frmUsuarios},
  frm_residencias in 'frm_residencias.pas' {frmResidencias},
  frm_ExportaGeneral in 'frm_ExportaGeneral.pas' {frmExportaGeneral},
  frm_ImportarDiarios in 'frm_ImportarDiarios.pas' {frmImportarDiarios},
  frm_ProcRegAvFisico in 'frm_ProcRegAvFisico.pas' {frmProcRegAvFisico},
  frm_Generadores_Barco in 'frm_Generadores_Barco.pas' {frmGeneradoresBarco},
  frm_EstimacionAlbum in 'frm_EstimacionAlbum.pas' {frmEstimacionAlbum},
  UnitEstimacion in 'UnitEstimacion.pas',
  frm_seleccion2 in 'frm_seleccion2.pas' {frmSeleccion2},
  frm_admonCatalogos in 'frm_admonCatalogos.pas' {frmAdmonCatalogos},
  frm_compara in 'frm_compara.pas' {frmComparativo},
  frm_comparativo in 'frm_comparativo.pas' {frmCompara},
  frm_EstimaInstalado in 'frm_EstimaInstalado.pas' {frmEstimaInstalado},
  inteligent_TLB in 'inteligent_TLB.pas',
  frm_AjustaAnexo in 'frm_AjustaAnexo.pas' {frmAjustaAnexo},
  frm_contratos in 'frm_contratos.pas' {frmContratos},
  frm_Pedidos in 'frm_Pedidos.pas' {frmPedidos},
  StoHtmlHelp in 'StoHtmlHelp.pas',
  frm_ConfiguraMail in 'frm_ConfiguraMail.pas' {frmConfiguraMail},
  frm_detalledeinstalacion in 'frm_detalledeinstalacion.pas' {frmDetalledeInstalacion},
  frm_Proyeccion2 in 'frm_Proyeccion2.pas' {frmProyeccion2},
  frm_Modulosxusuario in 'frm_Modulosxusuario.pas' {frmModulosxUsuario},
  frm_PrintReportesDiarios in 'frm_PrintReportesDiarios.pas' {frmPrintReportesDiarios},
  frm_tripulacion in 'frm_tripulacion.pas' {frmTripulacion},
  frm_partidasxisometrico in 'frm_partidasxisometrico.pas' {frmPartidasxIsometrico},
  frm_ReporteDiarioTurno2 in 'frm_ReporteDiarioTurno2.pas' {frmDiarioTurno2},
  frm_prorrateoPernocta in 'frm_prorrateoPernocta.pas' {frmProrrateoPernocta},
  frm_Fases in 'frm_Fases.pas' {frmFases},
  frm_AdmonyTiempos in 'frm_AdmonyTiempos.pas' {frmAdmonyTiempos},
  frm_ReporteDiario_Barco in 'frm_ReporteDiario_Barco.pas' {frmDiarioBarco},
  frm_tiposdeMovimiento in 'frm_tiposdeMovimiento.pas' {frmTiposdeMovimiento},
  frm_ordenes in 'frm_ordenes.pas' {frmOrdenes},
  frm_ordenesGral in 'frm_ordenesGral.pas' {frmOrdenesGeneral},
  Frm_DetalleOficioPersonal in 'Frm_DetalleOficioPersonal.pas' {FrmDetalleOficioPersonal},
  frm_Gantt2 in 'frm_Gantt2.pas' {frmcargaPrograma},
  Unit_Barras in 'Unit_Barras.pas',
  frm_CambioContrato in 'frm_CambioContrato.pas' {frmCambioContrato},
  frm_isometricos in 'frm_isometricos.pas' {frmIsometricos},
  frm_detalletiemposmuertos in 'frm_detalletiemposmuertos.pas' {frmdetallestiemposmuertos},
  frm_anexosCotemar in 'frm_anexosCotemar.pas' {frmAnexosCotemar},
  frm_GruposPersonal in 'frm_GruposPersonal.pas' {frmGruposPersonal},
  frm_Propiedades in 'frm_Propiedades.pas' {FrmPropiedades},
  frm_IntelChart in 'frm_IntelChart.pas' {IntelChart},
  frm_Graficador in 'frm_Graficador.pas' {frmGraficador},
  UnitExcel in 'UnitExcel.pas',
  UTChartMarco in 'UTChartMarco.pas',
  UTChartMouse in 'UTChartMouse.pas',
  frm_grupofamilias in 'frm_grupofamilias.pas' {frmGrupoFamilias},
  frm_basicos in 'frm_basicos.pas' {frmBasicos},
  frm_Almacenes in 'frm_Almacenes.pas' {frmAlmacenes},
  frm_actividades in 'frm_actividades.pas' {frmActividades},
  frm_bitacoraOptativa in 'frm_bitacoraOptativa.pas' {frmBitacoraOptativa},
  frm_EntradaAlmacen in 'frm_EntradaAlmacen.pas' {frmEntradaAlmacen},
  frm_SalidaAlmacen in 'frm_SalidaAlmacen.pas' {frmSalidaAlmacen},
  frm_EditorBitacoraDepartamental in 'frm_EditorBitacoraDepartamental.pas' {frmEditorBitacoraDepartamental},
  frm_AltaServidor in 'frm_AltaServidor.pas' {frmAltaServidor},
  frm_herramientas in 'frm_herramientas.pas' {frmHerramientas},
  UnitFactorPeriodo in 'UnitFactorPeriodo.pas',
  frm_RequisicionPerf in 'frm_RequisicionPerf.pas' {frmRequisicionPerf},
  UnitTSintaxFormulizer in 'UnitTSintaxFormulizer.pas',
  UnitTSemanticFormulizer in 'UnitTSemanticFormulizer.pas',
  frm_copiacontratos in 'frm_copiacontratos.pas' {Frmcopiaparametros},
  frm_embarcaciones in 'frm_embarcaciones.pas' {frmEmbarcaciones},
  UReporteDiarioMix in 'UReporteDiarioMix.pas',
  UIni in 'UIni.pas',
  frm_DetalleCaptura in 'frm_DetalleCaptura.pas' {DetalleCaptura},
  frm_EditaEstimacion in 'frm_EditaEstimacion.pas' {frmEditaEstimacion},
  frm_OpcionesAvances in 'frm_OpcionesAvances.pas' {frmOpcionesAvances},
  frm_estimaciones in 'frm_estimaciones.pas' {frmEstimaciones},
  frm_valida in 'frm_valida.pas' {frmValida},
  frm_plataformas in 'frm_plataformas.pas' {frmPlataformas},
  frm_Recursos_equipo in 'frm_Recursos_equipo.pas' {frmRecursosEquipo},
  frm_AdministrarBd in 'frm_AdministrarBd.pas' {FrmAdministrarBd},
  frm_Recursos_personal in 'frm_Recursos_personal.pas' {frmRecursosPersonal},
  frm_Recursos_movimientos in 'frm_Recursos_movimientos.pas' {frmRecursosMovimientos},
  frm_BusquedadeNotas in 'frm_BusquedadeNotas.pas' {frmBuscaComentarios},
  frm_cancelacion in 'frm_cancelacion.pas' {frmCancelacion},
  frm_AperturaEstimacionGral in 'frm_AperturaEstimacionGral.pas' {frmAperturaEstimacionGral},
  masUtilerias in 'masUtilerias.pas',
  UnitExcepciones in 'UnitExcepciones.pas',
  USelCol in 'USelCol.pas',
  frm_catalogoerrores in 'frm_catalogoerrores.pas' {frmCatalogoErrores},
  frm_Pernoctan in 'frm_Pernoctan.pas' {frmPernoctan},
  UDbGrid in 'UDbGrid.pas',
  frm_ActualizaAvancesRemotos in 'frm_ActualizaAvancesRemotos.pas' {frmActualizacionRemota},
  UFunctionsGHH in 'UFunctionsGHH.pas',
  frm_servidor in 'frm_servidor.pas' {frmdatos},
  frm_entradaanex in 'frm_entradaanex.pas' {frmentradaanex},
  unitmanejofondo in 'unitmanejofondo.pas',
  UnitValidaTexto in 'UnitValidaTexto.pas',
  frm_GraficaGerencialDX in 'frm_GraficaGerencialDX.pas' {frmGraficaGerencialDX},
  frm_PopUpPaquetes_p in 'frm_PopUpPaquetes_p.pas' {frmPopUpPaquetes_p},
  unitActivaPop in 'unitActivaPop.pas',
  frm_ReporteDiarioTurno in 'frm_ReporteDiarioTurno.pas' {frmDiarioTurno},
  UnitValidacion in 'UnitValidacion.pas',
  frm_graficaexplosion in 'frm_graficaexplosion.pas' {frmGraficaExplosion},
  frm_recursosxanexonuevos in 'frm_recursosxanexonuevos.pas' {frmRecursosxAnexonuevos},
  UnitTablasImpactadas in 'UnitTablasImpactadas.pas',
  frm_DespieceImagen in 'frm_DespieceImagen.pas' {frmDespieceImagen},
  frm_isometricos_nuevo in 'frm_isometricos_nuevo.pas' {frmIsometricosNuevo},
  frm_isometricos_grupo in 'frm_isometricos_grupo.pas' {frmIsometricosGrupos},
  frm_paquetesdepersonal in 'frm_paquetesdepersonal.pas' {frmPaquetePersonal},
  frm_paquetesdebasicos in 'frm_paquetesdebasicos.pas' {frmPaquetebasicos},
  frm_paquetesdeherramienta in 'frm_paquetesdeherramienta.pas' {frmPaqueteherramientas},
  UnitTBotonesPermisos in 'UnitTBotonesPermisos.pas' {,
  FrmMovtoPersonalxoficio in 'FrmMovtoPersonalxoficio.pas' {FrmMovtosPersonalxoficio},
  FrmMovtoPersonalxoficio in 'FrmMovtoPersonalxoficio.pas' {FrmMovtosPersonalxoficio},
  frm_sincinformes in 'frm_sincinformes.pas' {frmInformeSincronizacion},
  frm_OpcionesReporteProduccion in 'frm_OpcionesReporteProduccion.pas' {frmOpcionesReporteProduccion},
  frm_OpcionesGerencial in 'frm_OpcionesGerencial.pas' {frmOpcionesGerencial},
  frm_lista_personal in 'frm_lista_personal.pas' {frmLista_personal},
  frm_tripulacion_diaria in 'frm_tripulacion_diaria.pas' {frmTripulacionDiaria},
  frmGrupodeEgresos in 'frmGrupodeEgresos.pas' {frm_GrupodeEgresos},
  frm_Cuentas in 'frm_Cuentas.pas' {frmCuentas},
  frmCatalogoCuentas in 'frmCatalogoCuentas.pas' {frm_Catalogocuentasc},
  frmCatalogodeCuentas in 'frmCatalogodeCuentas.pas' {frm_CatalogoCuentas},
  frmCatalogoEgresos in 'frmCatalogoEgresos.pas' {frm_CatalogoEgresos},
  frmGraficabarrasIngresos in 'frmGraficabarrasIngresos.pas' {frm_graficabarrasIngresos},
  frmEstadodeCuenta in 'frmEstadodeCuenta.pas' {frm_EstadodeCuenta},
  frmGraficabarrasIngresosBancos in 'frmGraficabarrasIngresosBancos.pas' {frm_graficabarrasIngresosBancos},
  frmGraficabarrasIngresosvsEgresos in 'frmGraficabarrasIngresosvsEgresos.pas' {frm_graficasIngresosvsEgresos},
  frmEditEgresos in 'frmEditEgresos.pas' {frm_EditEgresos},
  frmEgresos in 'frmEgresos.pas' {frm_Egresos},
  frmBuscarProveedor in 'frmBuscarProveedor.pas' {frm_BuscarProveedor},
  frmReferenciarCheque in 'frmReferenciarCheque.pas' {frm_ReferenciarCheque},
  frmCargoA in 'frmCargoA.pas' {frm_cargoa},
  frmReferenciarChequeiva in 'frmReferenciarChequeiva.pas' {frm_ReferenciarChequeiva},
  frmGastos in 'frmGastos.pas' {frm_Gastos},
  frmBuscarEmpleado in 'frmBuscarEmpleado.pas' {frm_BuscarEmpleado},
  frmAbrirComprobacion in 'frmAbrirComprobacion.pas' {frm_AbrirComprobacion},
  frmConsultadeGastos_Empresa in 'frmConsultadeGastos_Empresa.pas' {frm_ConsultadeGastos_Empresa},
  frmGrafica in 'frmGrafica.pas' {frm_grafica},
  frmGraficabarras in 'frmGraficabarras.pas' {frm_graficabarras},
  frmReferenciarChequeComprobado in 'frmReferenciarChequeComprobado.pas' {frm_ReferenciarChequeComprobado},
  frmProveedoresPendientes in 'frmProveedoresPendientes.pas' {frm_ProveedoresPendientes},
  frmEquiposPorEmpleadoQuitar in 'frmEquiposPorEmpleadoQuitar.pas' {frm_EquiposPorEmpleadoQuitar},
  frm_Zincroligent in 'frm_Zincroligent.pas' {frmZincroligent},
  frm_zinc_parametros in 'frm_zinc_parametros.pas' {frmParametros: TDataModule},
  frm_Zinc_erroresDB in 'frm_Zinc_erroresDB.pas' {frmerroresDB},
  frm_Zinc_mensaje in 'frm_Zinc_mensaje.pas' {frmMensaje},
  frm_Zinc_editarConexiones in 'frm_Zinc_editarConexiones.pas' {frmeditarConexiones},
  frm_Zinc_erroresTabla in 'frm_Zinc_erroresTabla.pas' {frmerroresTabla},
  frm_EmpleadosGuardias in 'frm_EmpleadosGuardias.pas' {frmEmpleadosGuardias},
  frm_ComponentXFamilia in 'frm_ComponentXFamilia.pas' {frmComponentXFamilia},
  frm_almacenesporusuario in 'frm_almacenesporusuario.pas' {frmAlmacenesPorUsuario},
  frm_almacenesporcontrato in 'frm_almacenesporcontrato.pas' {frmAlmacenesPorContrato},
  frm_MarcasxSubFam in 'frm_MarcasxSubFam.pas' {frmMarcasxSubFam},
  frm_detallesubfamilias in 'frm_detallesubfamilias.pas' {frmdetallesubfamilias},
  frmConfiguracion in 'frmConfiguracion.pas' {frm_ConfiguracionCont},
  frm_ListadeAsistencia in 'frm_ListadeAsistencia.pas' {frmListadeAsistencia},
  frm_ModuloTraspaso in 'frm_ModuloTraspaso.pas' {frmModuloTraspaso},
  frmEquiposPorEmpleado in 'frmEquiposPorEmpleado.pas' {frm_EquiposPorEmpleado},
  frm_NuevoIdioma in 'frm_NuevoIdioma.pas' {frmNuevoIdioma},
  frm_ConfigAcceso in 'frm_ConfigAcceso.pas' {frmConfigAcceso},
  frm_DetalleGastosXEmpleados in 'frm_DetalleGastosXEmpleados.pas' {frmDetalleGastosXEmpleados},
  frm_EntradaEQSeguridad in 'frm_EntradaEQSeguridad.pas' {frmEntradaEQSeguridad},
  frm_EquipoSeguridad in 'frm_EquipoSeguridad.pas' {frmEquipoSeguridad},
  frmGraficabarrasIngresosvsEgresosxcuenta in 'frmGraficabarrasIngresosvsEgresosxcuenta.pas' {frm_graficasIngresosvsEgresosxcuent},
  Frm_ImportacionDatosRH in 'Frm_ImportacionDatosRH.pas' {FrmImportacionDatosRH},
  frm_configuracionVta in 'frm_configuracionVta.pas' {frmConfiguracionVTA},
  frm_CatalogoDatosBancarios in 'frm_CatalogoDatosBancarios.pas' {frmCatalogoDatosBancarios},
  frm_catalogoentidadeseducativas in 'frm_catalogoentidadeseducativas.pas' {frmCatalogoEntidadesEducativas},
  frm_catalogolocalidad_academico in 'frm_catalogolocalidad_academico.pas' {frmcatalogolocalidad_academico},
  frm_catalogoestatusequipo in 'frm_catalogoestatusequipo.pas' {frmCatalogoEstatusEquipo},
  frm_nuc_Organizacion in 'frm_nuc_Organizacion.pas' {frm_nucOrganizacion},
  frm_nivelorganizacion in 'frm_nivelorganizacion.pas' {frmnivelorganizacion},
  frm_RequisiondePersonal in 'frm_RequisiondePersonal.pas' {frmRequisiciondePersonal},
  AcroPDFLib_TLB in 'AcroPDFLib_TLB.pas',
  frm_TiposClientes in 'frm_TiposClientes.pas' {frmtiposclientes},
  frmReportesIngresoscias in 'frmReportesIngresoscias.pas' {frm_ReportesIngresoscias},
  Frm_CatalogoDePostulante in 'Frm_CatalogoDePostulante.pas' {FrmCatalogoDePostulante},
  frm_repositorio in 'frm_repositorio.pas' {frmrepositorio: TDataModule},
  frmCompanias in 'frmCompanias.pas' {frm_Companias},
  frm_Zinc_agregarConexion in 'frm_Zinc_agregarConexion.pas' {frmagregarConexion},
  frmDepositoscias in 'frmDepositoscias.pas' {frm_Depositoscias},
  principal in 'principal.pas' {frm_principal},
  UFrmVisorPdf in 'UFrmVisorPdf.pas' {FrmVisorPdf},
  Frm_VisorXml in 'Frm_VisorXml.pas' {FrmVisorXml},
  Func_Genericas in 'Func_Genericas.pas',
  UManagerDbUser in 'UManagerDbUser.pas' {FrmManagerDbUser},
  frm_PrecioDivisas in 'frm_PrecioDivisas.pas' {frmPrecioDivisas},
  frm_CatalogoVendedores in 'frm_CatalogoVendedores.pas' {frmCatVendedores},
  CFDI in 'PFE\CFDI.pas',
  PFacturaElectronica in 'PFE\PFacturaElectronica.pas',
  PFacturaElectronica_PAC in 'PFE\PFacturaElectronica_PAC.pas',
  PFacturaElectronica_Reglamentaciones in 'PFE\PFacturaElectronica_Reglamentaciones.pas',
  PAddenda_PEP in 'PFE\Addendas\PAddenda_PEP.pas',
  GeneradorCBB in 'PFE\GeneradorCBB\GeneradorCBB.pas',
  QuricolAPI in 'PFE\GeneradorCBB\QuricolAPI.pas',
  QuricolCode in 'PFE\GeneradorCBB\QuricolCode.pas',
  ClaseCertificadoSellos in 'PFE\GeneradorSello\ClaseCertificadoSellos.pas',
  ClaseOpenSSL in 'PFE\GeneradorSello\ClaseOpenSSL.pas',
  libeay32 in 'PFE\GeneradorSello\libeay32.pas',
  LibEay32Plus in 'PFE\GeneradorSello\LibEay32Plus.pas',
  OpenSSLUtils in 'PFE\GeneradorSello\OpenSSLUtils.pas',
  SelloDigital in 'PFE\GeneradorSello\SelloDigital.pas',
  PACFo in 'PFE\PAC\FO\PACFo.pas',
  wsFO in 'PFE\PAC\FO\wsFO.pas',
  PACFem in 'PFE\PAC\Fem\PACFem.pas',
  wsFem in 'PFE\PAC\Fem\wsFem.pas',
  frm_FormasPago in 'frm_FormasPago.pas' {frmFormasPago},
  frm_vtacotizaciones in 'frm_vtacotizaciones.pas' {frmVtaCotizaciones},
  frm_vtaTimeLine in 'frm_vtaTimeLine.pas' {frmvtaTimeLine},
  frm_firmasdigitales in 'frm_firmasdigitales.pas' {frmFirmasDigitales},
  frmDepositosciasTraspasos in 'frmDepositosciasTraspasos.pas' {frm_DepositosciasTraspasos},
  frm_vtaTCotizaciones in 'frm_vtaTCotizaciones.pas' {frmvtaTCotizaciones},
  frmCatalogoDeCargoA in 'frmCatalogoDeCargoA.pas' {frm_CatalogoDeCargoA},
  frmTipoVisita in 'frmTipoVisita.pas' {frm_TipoVisita},
  UTFrmIniciacionSaldo in 'UTFrmIniciacionSaldo.pas' {FrmIniciacionSaldo},
  unt_ventas in 'unt_ventas.pas',
  frm_ordenesctrlobra in 'frm_ordenesctrlobra.pas' {frmOrdenesCtrlObra},
  frm_ActividadesAnexoPU in 'frm_ActividadesAnexoPU.pas' {frmActividadesAnexoPU},
  frm_ActividadesAnexo2 in 'frm_ActividadesAnexo2.pas' {frmActividadesAnexo2},
  utileriascadmvo in 'utileriascadmvo.pas',
  frm_ImprimeContratos in 'frm_ImprimeContratos.pas' {frmImprimeContratos},
  frmCatalogoDePuestos in 'frmCatalogoDePuestos.pas' {frm_CatalogoDePuestos},
  frm_catalogoperiodospago in 'frm_catalogoperiodospago.pas' {frmCatalogoPeriodosPago},
  frm_catalogodiasdescanso in 'frm_catalogodiasdescanso.pas' {frmCatalogoDiasdescanso},
  frm_catalogohorariolabores in 'frm_catalogohorariolabores.pas' {frmCatalogoHorarioLabores},
  UTFrmCatalogoCargos in 'UTFrmCatalogoCargos.pas' {FrmCatalogoCargos},
  frm_catalogomodulos in 'frm_catalogomodulos.pas' {frmCatalogoModulos},
  frm_asigna_salario in 'frm_asigna_salario.pas' {frmAsignaSalario},
  frmDoctosXcategoria in 'frmDoctosXcategoria.pas' {Frm_DoctosxCategoria},
  frmtipopersonal in 'frmtipopersonal.pas' {frm_tipopersonal},
  UTFrmGuardias in 'UTFrmGuardias.pas' {FrmGuardias},
  frm_Colmena in 'frm_Colmena.pas' {frmColmena},
  UnitRH in 'UnitRH.pas',
  UnitMetodos in 'UnitMetodos.pas',
  URegistro in 'Comunes Nomina\URegistro.pas',
  UTFrmPeriodosGuardia in 'UTFrmPeriodosGuardia.pas' {FrmPeriodosGuardia},
  UTFrmEvaluarEmpleados in 'UTFrmEvaluarEmpleados.pas' {FrmEvaluarEmpleados},
  frm_indirectos in 'frm_indirectos.pas' {frmIndirectos},
  UInteliDialog in 'Comunes Nomina\UInteliDialog.pas' {InteliDialog},
  UTFrmDepartamentos in 'UTFrmDepartamentos.pas' {FrmDepartamentos},
  UTfrmCatalogoSalarios in 'UTfrmCatalogoSalarios.pas' {FrmCatalogoSalarios},
  frm_catalogoprofesiones in 'frm_catalogoprofesiones.pas' {frmCatalogoProfesiones},
  frm_contratosxusuario in 'frm_contratosxusuario.pas' {frmContratosxUsuario},
  frm_ReporteErrores in 'frm_ReporteErrores.pas' {frmRepErrores},
  frm_catactualizaciones in 'frm_catactualizaciones.pas' {frm_actualizaciones},
  frmBancos in 'frmBancos.pas' {frm_BancosGral},
  frmEmpleados in 'frmEmpleados.pas' {frm_Empleados},
  frmDetalleErrores in 'frmDetalleErrores.pas' {frm_DetalleError},
  frmCatalogoDeCategoriasDeEquipos in 'frmCatalogoDeCategoriasDeEquipos.pas' {frm_CatalogoDeCategoriasDeEquipos},
  frmCatalogoDeEquipos in 'frmCatalogoDeEquipos.pas' {frm_CatalogoDeEquipos},
  UTFrmWizardGroup in 'UTFrmWizardGroup.pas' {FrmWizardGroup},
  rhh_genericclasses in 'rhh_genericclasses.pas',
  UFrmHE in 'UFrmHE.pas' {FrmHE},
  UTFrmHistorialEquipoSeguridad in 'UTFrmHistorialEquipoSeguridad.pas' {FrmHistorialEquipoSeguridad},
  UTFrmProgramaDeSalud in 'UTFrmProgramaDeSalud.pas' {FrmProgramaDeSalud},
  frm_ImprimeDocumentos in 'frm_ImprimeDocumentos.pas' {frmImprimeDocumentos},
  UnitGenerales in 'UnitGenerales.pas',
  frm_Medidas in 'frm_Medidas.pas' {frmMedidas},
  frm_respaldo in 'frm_respaldo.pas' {frmObtenerRespaldo},
  frm_respaldocompleto in 'frm_respaldocompleto.pas' {frmRespaldoCompleto},
  frm_montarespaldo in 'frm_montarespaldo.pas' {frmMontarRespaldo};

{$R *.TLB}

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'Sistema de Recursos Humanos';
  Application.HelpFile := '';
  Application.CreateForm(Tconnection, connection);
  Application.CreateForm(TfrmInteligent, frmInteligent);
  Application.CreateForm(Tfrmacceso, frmacceso);
  Application.CreateForm(TfrmSeguridad, frmSeguridad);
  Application.CreateForm(TfrmColmena, frmColmena);
  Application.CreateForm(TfrmAcerca, frmAcerca);
  Application.CreateForm(TfrmSeleccion2, frmSeleccion2);
  Application.CreateForm(TFrmPropiedades, FrmPropiedades);
  Application.CreateForm(Tfrmrepositorio, frmrepositorio);
  Application.CreateForm(TInteliDialog, InteliDialog);
  Application.CreateForm(TfrmObtenerRespaldo, frmObtenerRespaldo);
  Application.CreateForm(TfrmRespaldoCompleto, frmRespaldoCompleto);
  Application.CreateForm(TfrmMontarRespaldo, frmMontarRespaldo);
  Application.Run;
end.




